from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class FailedCheck(BaseModel):
    criterion: str = Field(
        description="The specific rubric dimension that failed (e.g., 'Jargon Handling', 'Example-Based')."
    )
    reason: str = Field(
        description="Detailed explanation of why the criterion failed, quoting the problematic sentence or jargon."
    )
    suggestion: str = Field(
        description="Actionable correction advice for the Regenerator agent."
    )


class EvaluationRubric(BaseModel):
    """Strict binary (Pass/Fail) evaluation rubric across 6 core pedagogical dimensions."""

    accuracy: bool = Field(
        description="Pass if the lesson is factually and conceptually accurate with zero misinformation."
    )
    beginner_friendly: bool = Field(
        description="Pass if language is at A2/B1 level with short sentences suitable for a 12th-grade graduate."
    )
    example_based: bool = Field(
        description="Pass if a concrete, relatable real-world example (e.g. library, textbook) is provided."
    )
    jargon_handling: bool = Field(
        description="Pass if terms like 'Vector', 'Embedding', 'LLM', etc. have immediate inline definitions."
    )
    core_concepts: bool = Field(
        description="Pass if all three stages (Retrieval, Augmentation, Generation) are clearly taught."
    )
    teaching_flow: bool = Field(
        description="Pass if structured cleanly into What, Why, How, Example, and Summary."
    )
    overall_pass: bool = Field(
        description="True ONLY if every single dimension above is True. Zero partial credit."
    )
    failed_checks: List[FailedCheck] = Field(
        default_factory=list,
        description="List of failing criteria with specific reasons and suggestions. Empty if overall_pass is True.",
    )
    evaluator_notes: Optional[str] = Field(
        default="",
        description="Summary feedback from the evaluator.",
    )


class LessonPlan(BaseModel):
    """Structured outline generated by the Planner Agent."""

    topic: str
    target_audience: str = "Indian 12th-grade graduate (A2/B1 English)"
    what: str = Field(description="High-level definition and intuitive overview")
    why: str = Field(description="The problem it solves and real-world significance")
    how: str = Field(description="Step-by-step mechanism (Retrieval, Augmentation, Generation)")
    example: str = Field(description="Everyday analogy/scenario grounding the concept")
    summary: str = Field(description="Key takeaways and recap")


class RejectionLogEntry(BaseModel):
    attempt: int
    status: str
    failed_checks: List[Dict[str, str]]
    corrections: List[str]


class GenerationRequest(BaseModel):
    topic: str = Field(
        default="Introduction to RAG (Retrieval-Augmented Generation)",
        description="Topic for lesson generation",
    )


class GenerationResponse(BaseModel):
    topic: str
    status: str
    attempts: int
    lesson_content: str
    rejection_log: List[Dict[str, Any]]
    reflection_feedback: Optional[str] = None
